require 'fog/openstack'
require 'parallel'

require 'manageiq/providers/openstack/legacy/openstack_handle/handled_list'
require 'manageiq/providers/openstack/legacy/openstack_handle/handle'

require 'manageiq/providers/openstack/legacy/openstack_handle/baremetal_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/compute_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/event_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/identity_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/image_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/introspection_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/metering_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/metric_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/network_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/nfv_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/orchestration_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/storage_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/volume_delegate'
require 'manageiq/providers/openstack/legacy/openstack_handle/workflow_delegate'
